-- damaging_spells.lua
-- List of damaging spell IDs for SleepTimers addon
return {
    [21] = true,   -- Stone
    [22] = true,   -- Water
    [23] = true,   -- Aero
    [24] = true,   -- Fire
    [25] = true,   -- Blizzard
    [26] = true,   -- Thunder
    [27] = true,   -- Stone II
    [28] = true,   -- Water II
    [29] = true,   -- Aero II
    [30] = true,   -- Fire II
    [31] = true,   -- Blizzard II
    [32] = true,   -- Thunder II
    [33] = true,   -- Stone III
    [34] = true,   -- Water III
    [35] = true,   -- Aero III
    [36] = true,   -- Fire III
    [37] = true,   -- Blizzard III
    [38] = true,   -- Thunder III
    [39] = true,   -- Stonega
    [40] = true,   -- Waterga
    [41] = true,   -- Aeroga
    [42] = true,   -- Firaga
    [54] = true,   -- Banish
    [115] = true,  -- Banish II
    [117] = true,  -- Holy
    [144] = true,  -- Stone IV
    [145] = true,  -- Water IV
    [146] = true,  -- Aero IV
    [147] = true,  -- Fire IV
    [148] = true,  -- Blizzard IV
    [149] = true,  -- Thunder IV
    [150] = true,  -- Stonega II
    [151] = true,  -- Waterga II
    [152] = true,  -- Aeroga II
    [153] = true,  -- Firaga II
    [154] = true,  -- Blizzaga II
    [155] = true,  -- Thundaga II
    [156] = true,  -- Stonega III
    [157] = true,  -- Waterga III
    [158] = true,  -- Aeroga III
    [159] = true,  -- Firaga III
    [160] = true,  -- Blizzaga III
    [161] = true,  -- Thundaga III
    [162] = true,  -- Stone V
    [163] = true,  -- Water V
    [164] = true,  -- Aero V
    [165] = true,  -- Fire V
    [166] = true,  -- Blizzard V
    [167] = true,  -- Thunder V
    [168] = true,  -- Stonega IV
    [169] = true,  -- Waterga IV
    [170] = true,  -- Aeroga IV
    [171] = true,  -- Firaga IV
    [172] = true,  -- Blizzaga IV
    [173] = true,  -- Thundaga IV
    [174] = true,  -- Stone VI
    [175] = true,  -- Water VI
    [176] = true,  -- Aero VI
    [177] = true,  -- Fire VI
    [178] = true,  -- Blizzard VI
    [179] = true,  -- Thunder VI
    [180] = true,  -- Stonega V
    [181] = true,  -- Waterga V
    [182] = true,  -- Aeroga V
    [183] = true,  -- Firaga V
    [184] = true,  -- Blizzaga V
    [185] = true,  -- Thundaga V
    [186] = true,  -- Comet
    [187] = true,  -- Meteor
    [188] = true,  -- Meteor II
    [189] = true,  -- Flare
    [190] = true,  -- Flare II
    [191] = true,  -- Freeze
    [192] = true,  -- Freeze II
    [193] = true,  -- Tornado
    [194] = true,  -- Tornado II
    [195] = true,  -- Quake
    [196] = true,  -- Quake II
    [197] = true,  -- Burst
    [198] = true,  -- Burst II
    [199] = true,  -- Flood
    [200] = true,  -- Flood II
    [201] = true,  -- Flare III
    [202] = true,  -- Freeze III
    [203] = true,  -- Tornado III
    [204] = true,  -- Quake III
    [205] = true,  -- Burst III
    [206] = true,  -- Flood III
    [207] = true,  -- Geohelix
    [208] = true,  -- Hydrohelix
    [209] = true,  -- Anemohelix
    [210] = true,  -- Pyrohelix
    [211] = true,  -- Cryohelix
    [212] = true,  -- Ionohelix
    [213] = true,  -- Noctohelix
    [214] = true,  -- Luminohelix
    [215] = true,  -- Helix II
    [218] = true,  -- Banish III
    [219] = true,  -- Banishga
    [220] = true,  -- Banishga II
    [221] = true,  -- Banish IV
    [222] = true,  -- Holy II
    [223] = true,  -- Holy III
    [224] = true,  -- Dia
    [225] = true,  -- Dia II
    [226] = true,  -- Dia III
    [227] = true,  -- Dia IV
    [228] = true,  -- Bio
    [229] = true,  -- Bio II
    [230] = true,  -- Bio III
    [231] = true,  -- Bio IV
    [232] = true,  -- Poison
    [233] = true,  -- Poison II
    [234] = true,  -- Poison III
    [244] = true,  -- Poisonga
    [245] = true,  -- Poisonga II
    [246] = true,  -- Poisonga III
    [498] = true,  -- Drain
    [499] = true,  -- Drain II
    [501] = true,  -- Aspir
    [536] = true,  -- Aspir II
    [570] = true,  -- Drain III
    [612] = true,  -- Aspir III
    [632] = true,  -- Impact
    [637] = true,  -- Death
    [687] = true,  -- Kaustra
    [695] = true,  -- Stoneja
    [705] = true,  -- Waterja
    [736] = true,  -- Aeroja
    [748] = true,  -- Firaja
    [769] = true,  -- Blizzaja
    [799] = true,  -- Thundaja
    [834] = true,  -- Banishga III
    [835] = true,  -- Banishga IV
    [838] = true,  -- Banish V
    [839] = true,  -- Holy IV
    [849] = true,  -- Comet II
    [850] = true,  -- Meteor III
    [851] = true,  -- Meteor IV
    [852] = true,  -- Meteor V
    [853] = true,  -- Meteor VI
    [854] = true,  -- Meteor VII
    [860] = true,  -- Absorb-STR
    [862] = true,  -- Absorb-DEX
    [868] = true,  -- Absorb-INT
    [870] = true,  -- Absorb-CHR
    [880] = true,  -- Absorb-ACC
}
